name: Check Kindlefy

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check Kindlefy
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Packages
        run: npm install

      - name: Run Kindlefy Integration and Unit tests
        run: npm run test:ci

      - name: Run Kindlefy Github Action
        uses: ./
        with:
          kindle_email: 'demo@kindle.com'
          sender: '[]'
          sources: '[{ "type": "manga", "name": "One Piece" }, { "type": "rss", "url": "https://dev.to/feed" }]'
